finos/legend-engine-ide-client-vscode

.github/workflows/check-build.yml
package-lock.json
package.json

Update package name

---

.github/workflows/manual__release.yml
package-lock.json
package.json

Update release script and bump version to 0.0.2

---

server/pom.xml

Ensure all dependencies are provided

---

server/pom.xml

Update server to 0.0.5

---

server/pom.xml

Uptick server version  to 0.0.8

---

scripts/maven/updateEngineVersion.js
server/pom.xml

Closes https://github.com/finos/legend-engine-ide-lsp/issues/140

Ensure pom provides SDLC dependencies

---

package-lock.json
package.json
src/LegendLanguageClient.ts
src/components/grid/AgGrid.tsx
src/components/grid/AgGridRenderer.tsx
src/components/grid/GridUtils.ts
src/components/grid/ServerSideDataSource.ts
src/components/parameters/InstanceValueEditor.tsx
src/components/parameters/ParametersEditor.tsx
src/components/parameters/ParametersEditorRenderer.tsx
src/extension.ts
src/model/FunctionTDSRequest.ts
src/model/TDSRequest.ts
src/results/ExecutionResultHelper.ts
src/results/FunctionLegendExecutionResult.ts
src/results/LanguageClientProgressResult.ts
src/results/LegendExecutionResultSerializationHelper.ts
src/results/TDSLegendExecutionResult.ts
src/utils/AssertionUtils.ts
src/utils/Const.ts
src/utils/VsCodeUtils.ts
webpack.config.js

Dependes on finos/legend-engine-ide-lsp#143

Support pushdown tds operations using ag-grid

---

src/extension.ts
src/utils/LegendWebViewProvider.ts

https://github.com/finos/legend-engine-ide-client-vscode/assets/87973126/38323557-e187-4d31-8327-09fb81a7d629

Focus results panel when results are returned

---

.github/workflows/test.yml
.gitignore
package-lock.json
package.json
src/tests/mockUtils/Mock_LanguageClient.ts
src/tests/runTest.ts
src/tests/suite/index.ts
src/tests/suite/utils/AssertionUtils.test.ts
src/tests/suite/utils/LegendTreeProvider.test.ts
src/tests/suite/utils/LegendWebViewProvider.test.ts

Setup basic test suite
- Add tests for assertion utils
- Add tests to check execution tree is getting built correctly
- Add tests to check command execution for webview

Setup initial test suite

---

src/components/grid/AgGrid.tsx
src/components/grid/AgGridRenderer.tsx
src/components/grid/GridUtils.ts
src/components/grid/ServerSideDataSource.ts
src/model/TDSRequest.ts
src/results/ExecutionResultHelper.ts

Minor changes to server side ag-grid operations

---

src/components/grid/AgGrid.tsx
src/components/grid/AgGridRenderer.tsx
src/components/grid/GridUtils.ts
src/components/grid/ServerSideDataSource.ts
src/model/TDSRequest.ts
src/results/ExecutionResultHelper.ts

Reverts finos/legend-engine-ide-client-vscode#43

Revert "Minor changes to server side ag-grid operations"

---

.github/workflows/check-build.yml
.github/workflows/manual__release.yml
package.json
server/pom.xml
src/extension.ts
src/results/LanguageClientProgressResult.ts

- New command to show logs
- Update lsp version to 0.0.9
- Add publishing to openvsx

Prepare for next release

---

package.json
scripts/copyright/COPYRIGHT_HEADER.txt
scripts/copyright/checkCopyrightHeaders.js
src/extension.ts
src/model/TextInterval.ts
src/model/TextLocation.ts
src/model/TextPosition.ts
src/results/ExecutionResultHelper.ts
src/tests/suite/utils/LegendTreeProvider.test.ts
src/utils/Const.ts
src/utils/LegendTreeProvider.ts

Support executing all test cases

---

package.json
server/pom.xml
src/LegendLanguageClient.ts
src/extension.ts
src/model/ExecuteTestRequest.ts
src/model/LegendTest.ts
src/model/LegendTestAssertionResult.ts
src/model/LegendTestExecutionResult.ts
src/testController.ts
src/utils/Const.ts

Integrate Legend testables with VS Code TestController for better user experience

Implement TestController to provide a better experience when executing test cases

---

server/pom.xml
src/LegendLanguageClient.ts
src/extension.ts
src/utils/Const.ts

Improvement
This MR add support for a virtual file system, legend-vfs, that will allow users to navigate to legend code that is inside dependent projects.

Support for virtual file system to allow display legend code from dependencies

---

server/pom.xml

Update for next server version, 0.1.1

---

.gitlab-ci.yml
.gs-project.yml
src/extension.ts
src/utils/Const.ts
tsconfig.json

Implement function activator snippets

Implement function activator snippets

---

package.json
server/pom.xml

Improvement
Update to latest changes on the language server, including the support for 2 new configuration properties.
These properties enable better SDLC integration for Studio projects.
Fixes #

Update legend language server to 0.2.1

---

server/pom.xml

Bug Fix
Update to 0.2.2 to fix dependency handling bug where these could not be parsed / compiled
Fixes #

Update server to 0.2.2

---

server/pom.xml

Update server to 0.2.3

---

src/extension.ts
src/utils/Const.ts

Improvement
Services and functions to share the same execution command/flow.
Fixes #

Support execution of services

---

package.json
src/extension.ts

Make easy finding the extension output

---

server/pom.xml
src/extension.ts

Open grid inside VSCode simple browser

---

server/pom.xml

Update to lsp server 0.2.7

---

.gitignore
.vscodeignore
package.json
src/components/function/FunctionResultsEditorRenderer.tsx
src/components/grid/AgGridRenderer.tsx
src/extension.ts
src/results/ExecutionResultHelper.ts
src/webviews/DiagramWebView.ts
src/webviews/FunctionResultsWebView.ts
webpack.config.js

Improvement
The size of vsix is around 200+ MB currently. This change reduces it to less than 20 MB.

bundles the extension for smaller vsix size

---

package.json
src/extension.ts

Allow users to provide VM args for the language server

---

package.json
src/extension.ts

Add config for plan executor configuration

Add config for plan executor configuration

---

.github/workflows/check-build.yml
.github/workflows/check-code.yml
.github/workflows/cve-scanning.yml
.github/workflows/license-scanning.yml
.github/workflows/manual__prepare-new-release.yml
.github/workflows/manual__release.yml
.github/workflows/test.yml
package.json
src/LegendLanguageClient.ts
src/extension.ts
src/utils/Const.ts

Introduce command to refactor per Studio/SDLC requirements

---

src/extension.ts

Pass workspace folders as REPL args

Pass workspace folders as REPL args

---

src/extension.ts

Bugfixes for REPL integration with workspace folders

---

server/pom.xml

Upgrade LSP@0.5.1

---

package.json
src/extension.ts

Add PCT report to extension

---

server/pom.xml

Upgrade lsp@0.6.2

---

server/pom.xml

Update LSP server to 0.6.3

---

package-lock.json
package.json
src/LegendLanguageClient.ts
src/components/diagram/DiagramRendererRoot.tsx
src/conceptTree.ts
src/extension.ts
src/utils/Const.ts
src/webviews/DiagramWebView.ts
webpack.config.js

adds diagram editor

---

server/pom.xml

Update lsp server

---

server/pom.xml

Upgrade lsp@0.6.5

---

src/components/diagram/DiagramEditorCanvas.tsx
src/components/diagram/DiagramEditorHeader.tsx

minor bug fix

---

package.json
src/extension.ts

Support for repl vmargs and other exec settings

---

server/pom.xml

Update lsp server version

---

src/extension.ts

- Improvement
1. Adds code lens to view/edit the diagram
Clicking on the codlens, open the diagram UI.
2. Adds diagram name to the webview tab.
3. If user tries to reopen already opened diagram, then tab containing the existing diagram is revealed.

adds codelens to view/edit diagram

---

server/pom.xml

updating ide lsp version to 0.8.0

updating ide lsp version to 0.8.0

---

server/pom.xml

Update pom.xml for release
Fixes #

Update pom.xml for release

---

server/pom.xml

Upgrade lsp@0.10.0

---

package.json
src/extension.ts

Rename PCT report command

---

server/pom.xml

Upgrade lsp@0.11.0

---

.github/workflows/cve-scanning.yml
src/purebook/purebook.ts

Assign supported languages

---

server/pom.xml
src/webviews/utils.ts

Improvement
Update LSP vesrion
Fixes #

Update LSP version

---

server/pom.xml

update lsp-ide@0.13.0 version

---

server/pom.xml

Upgrade LSP@0.15.1

---

.vscode/settings.json
eslint.config.mjs
package-lock.json
package.json
src/components/ComponentRouter.tsx
src/components/dataCube/DataCubeRenderer.tsx
src/graph/V1_LSPEngine.ts
src/purebook/LSPDataCubeEngine.ts
src/purebook/PurebookCubeRenderer.tsx
src/purebook/PurebookRendererRoot.tsx
src/purebook/purebook.ts
src/utils/Const.ts
src/webviews/DataCubeWebView.ts
src/webviews/utils.ts

Improvement
This PR adds functionality to allow opening a purebook DataCube output in a new tab so it can be viewed in a bigger window.
Fixes #
Yes
Opening DataCube in new tab:
Clicking open in new tab button opens existing tab if present:

Allow opening purebook DataCube in a new tab

---

.github/workflows/manual__release.yml

Bug Fix
This PR fixes a bug in the bump versions step of the manual__release workflow where we were pushing to the wrong branch instead of the main branch.
Fixes #
No

Fix bump versions step in manual__release worklow

---

CONTRIBUTING.md
README.md
packages/extension/README.md

Improvement
This PR updates the README files and CONTRIBUTING guide to match the current state of the project and remove duplicate text.
Fixes #
No

Update READMEs and CONTRIBUTING guide

---

.github/workflows/manual__release.yml
package.json
packages/shared/.npmignore
packages/shared/package.json

Bug Fix
This PR publishes the shared package to npm. Because the client package depends on the shared package, the shared package must also be published to npm in order to install the client package in other projects.
Fixes #
No

Publish shared package to npm

---

packages/extension/src/webviews/utils.ts

Bug Fix
This PR fixes a bug where if the user provided a local file (non http/https URL) for the studio forms file, VS Code would fail to load it properly because it would fetch it as an html document instead of a javascript file.
Fixes #
Yes

Handle forms file being a local file

---

packages/extension/server/pom.xml

Upgrade LSP @0.16.0

---

packages/extension/webpack.config.js

Bug Fix
This PR fixes the react alias in the webpack config.
Fixes #
No

Fix react alias in webpack config

---

packages/client/src/components/ComponentRouter.tsx
packages/client/src/components/WebViewRoot.tsx

Bug Fix
This PR fixes a bug where presets/plugins passed into the ComponentRouter were incorrectly destructured and thus always came through as undefined.
Fixes #
No

Fix passing plugins/presets to ComponentRouter

---

packages/extension/server/pom.xml

Improvement
Update LSP version to 0.17.0
Fixes #
No

Update LSP to 0.17.0

---

packages/extension/server/pom.xml

Update LSP to v0.19.0

---

packages/extension/server/pom.xml

Update server version to 0.21.0
